### ISSUE TITLE
Move Module Creation command from Kyma CLI to the modulectl

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/modulectl#10]
**Description**

The functionality of creating a new module should be imported from the CLI

**Acceptance Criteria**
- Implement Module Create functionality
- Don't copy the Kyma CLI code
     - Stick to the Cobra framework
     - Adhere to principles presented here: https://github.com/kyma-project/cli/issues/1908
- Covered with unit-tests
- Ensure validations for module create command also cover module scaffolding command
  - when refactoring moduleConfig and making it a public type, update `tests/e2e/create/scaffold/scaffold_test.go` to use the public type instead the copied one.

**Comment by janmedrek** [comment]
Blocked by: https://github.com/kyma-project/modulectl/issues/9

**Comment by c-pius** [comment]
Issue split:

- #26 
- #27 
- #28
