### ISSUE TITLE
Wrap errors from newest to oldest

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#105]
**Description**

Sometimes we wrap errors like `<older>: <newer>`, e.g., in: https://github.com/kyma-project/modulectl/blob/main/internal/service/create/create.go#L222

We should rather wrap them in the different order `<newer>: <older>`

Also take care of reformulating err message then if the order changes to make more sense.

**Reasons**

See Google Style guide [Placement of %w in errors](https://google.github.io/styleguide/go/best-practices.html#placement-of-w-in-errors). It is good practice to wrap like `<newer>: <older>` so that the printed error reads from newer to older (i.e., generic to specific) and so that the print is aligned with the unwrapping of the error.

**AC**

- [x] investigated whether possible to configure a linter catching this, if so, configured accordingly
  - check if the linter is maybe disabled in the current config
- [x] all occurrences in the code fixed

**Attachments**

**Comment by medmes** [comment]
After some investigation regarding the linter, the `errorlint` and `errwrap` are already enabled by default except the test files. those linters already check if the error are already wrapped. I suggest, in the next PRs that we keep an eye on error handling and avoid the putting the nested error in the beginning of the parent error.

**Comment by nesmabadr** [comment]
We could also write a step using bash in the linter GitHub Action which fetches any values that don't match the pattern with err at the end, something like `grep -nr 'fmt.Errorf("' . | grep -v '%w"'` and it should fail if there are any.
