### ISSUE TITLE
Configure build jobs for modulectl

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#18]
**Description**

We need to create a build job. The configuration can be based on one of the existing jobs: https://github.com/kyma-project/test-infra/tree/main/prow/jobs/kyma-project. Once there, the job should also be linked from the Pipeline Check tab in the project.

Since Prow will be sunset soon we should use GH Actions

We could use similar setup as the old Kyma CLI was using (without the Homebrew part), Neighbors can provide more info on the best location to store the build artifact

**Reasons**

Compliance with security requirements and being able to release modulectl at some point.

**Attachments**

**Comment by jeremyharisch** [comment]
Let's clarify with neighbours, since PROW will be sunset end of July. PLease clarify how we want to continue here and directly start using GH-Actions

**Comment by lindnerby** [comment]
Closing this, build and release jobs can be found [here](https://github.com/kyma-project/modulectl/actions).
