### ISSUE TITLE
[ModuleCatalog] ModuleTemplate's `metadata.name` is `<module-name>-<version>`

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#62]
## Description

Use the `module-config.yaml`'s `version` instead of the `channel` to generate the ModuleTemplate's `.metadata.name` attribute.

## Reason

New module templates will follow a new naming schema. See https://github.com/kyma-project/lifecycle-manager/issues/1681 section "Requirements for ModuleTemplates".

## AC

- [x] given a module config like
  ```yaml
  name: kyma-project.io/module/template-operator
  version: 1.0.0
  ```
- [x] the generate module template should look like
  ```yaml
  metadata:
    name: template-operator-1.0.0
  ```
- [x] Adapt E2E tests to cover new naming scheme
- [x] Clarify process of handover and note it down in https://github.com/orgs/kyma-project/projects/30/views/13?pane=issue&itemId=83269799

**Comment by lindnerby** [comment]
Handover clarified.
