### ISSUE TITLE
Remove support for local manifest

### ISSUE THREAD

**Issue by c-pius** [kyma-project/modulectl#66]
**Description**

We want to deprecate the option for providing `manifest` as local file (TODO: also other things like `defaultCR`?). Users should always provide a link to the released file.

**Reasons**

Fewer options to support. Fewer mistakes to make.

**ACs**

- [x] `manifest` MUST be a URL

**Attachments**

**Comment by nesmabadr** [comment]
Already resolved by https://github.com/kyma-project/modulectl/commit/ab02b3fb44d37a5bcfec9874b3091c155f8ca8eb
